### PR TITLE
fix: Guide for display lookup list

### LINKED ISSUE #1922: [Docs]: Guide to display and lookup list data
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

_No response_

### Discord/slack/intercom Link

_No response_

### Describe the problem and improvement.

Write a guide to display and lookup list data.

### PR DESCRIPTION
**Pull request by rashmi-sahoo-git**
closes #1922 
## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

### CODE REVIEW

File: website/sidebars.js [hunk 1]
```diff
@@ -329,6 +329,7 @@ const sidebars = {
               label: 'Display Data',
               items: [
                 `build-apps/how-to-guides/display-search-and-filter-table-data`,
+                `build-apps/how-to-guides/display-search-and-filter-list-data`,
```
Comment (danciaclara) [inline website/sidebars.js:332]: put this just above serverside pagination list

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 2]
```diff
@@ -0,0 +1,67 @@
+---
+description: This page shows you how to display and lookup data in a List widget. 
+---
+
+# Display and Lookup Data in List
+
+<div style={{ position: "relative", paddingBottom: "calc(50.520833333333336% + 41px)", height: "0", width: "100%" }}>
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:7]: In arcade you are dropping a container with a list and a text widget. and that looks confusing to users. in the steps, the search part is shown towards the end. also we can skip the search and filter pieces in the arcade. Focus mainly on the display list items

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+  </iframe>
+</div>
+
+This page shows you how to display and lookup data in a List widget.
+## Prerequisites
+- A datasource containing the data to display and filter. See [Connect datasource](/getting-started/tutorials/the-basics/connect-query-display-data#connect-datasource) for a tutorial. For the list of datasources supported by Appsmith, see [Datasources](/connect-data/reference).
+
+## Display data
+To display data in a List widget, follow these steps:
+1. In the widget's property pane, set the **Items** property under **Data**.
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:18]: post this step, don't users have to individually configure the list item widgets using `currentItem`. that is missing both in arcade and here

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+   {{fetch_users.data}}
+   ```
+   Where `fetch_users` is the query to fetch data from the connected datasource.
+
+   To nest lists within a List widget, see [Create Nested Lists](build-apps/how-to-guides/Create-Nested-Lists).
+   
+2. To set up pagination, enable the **Server side pagination** property for pagination. To set up the server-side pagination manually, follow the instructions in [Setup Server-Side Pagination on List](/build-apps/how-to-guides/Setup-Server-side-Pagination-on-List).
+
+
+## Customize items
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:31]: this section seems unecessary. it can be mentioned in short in the first section where you should show how to bind data to the list items.

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+1. To rearrange widgets within a List item, drag and drop them within the first item to rearrange the order. Once you arrange the widgets in the first List item, the subsequent items automatically update with the same arrangement.
+2. To customize each widget within the List, go to the widget's property pane and set the properties like **Data**, **Visible**, and configure events associated with the widgets.
+
+
+## Format list cells
+Highlighting list cells enables you to visually distinguish specific cells from others.
+For example, user management applications highlight active users in green when displaying a list of users to differentiate them quickly.
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:38]: avoid mentioning the usecase

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+
+   Example:
+   ```jsx
+   {{currentItem.user_status === "active" ? "green" : "orange"}}
+   ```
+   To customize each item of the List widget, see [Style properties](/reference/widgets/list#style-properties).
+
+## Configure search on List
+To configure search on List, follow these steps:
+1. Drop a Container widget and then add a List widget and an Input widget to the Container.
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:51]: why do we need a container here?

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+2. Bind data to the List by following the steps in the [Display data](#display-data) section.
+3. Add a JS object and add code to filter the List data based on the search text in the Input widget.
```
Comment (danciaclara) [inline website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:53]: search and filter are two different operation. this section is External Search (using Input). you need to have a separate section for External Filter (using Select )

**Review by danciaclara — CHANGES_REQUESTED** [review]

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md (hunk 2 above)
Comment (rashmi-sahoo-git) [reply website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md:7]: This arcade serves as an important piece when users want to implement search. Shall we move the arcade to the search section?

File: website/sidebars.js (hunk 1 above)
Comment (rashmi-sahoo-git) [reply website/sidebars.js]: Done

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md (hunk 4 above)
Comment (rashmi-sahoo-git) [reply website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md]: Done

File: website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md (hunk 7 above)
Comment (rashmi-sahoo-git) [reply website/docs/build-apps/how-to-guides/display-search-and-filter-list-data.md]: Done.

**Review by danciaclara — APPROVED** [review]
